import './global.css';
import { Rubik } from 'next/font/google';

//components
import Navbar from './components/Navbar.jsx';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Next 13 app',
  description: 'Generated by next',
};

export default function RootLAyout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
